//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyEntities : DbContext
    {
        public MyEntities()
            : base("name=MyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CRITERIA> CRITERIA { get; set; }
        public virtual DbSet<CV_ITEM> CV_ITEM { get; set; }
        public virtual DbSet<CV_ITEM_LINK> CV_ITEM_LINK { get; set; }
        public virtual DbSet<CV_ITEM_STATUS> CV_ITEM_STATUS { get; set; }
        public virtual DbSet<CV_USER> CV_USER { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
    }
}
