//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public long LOG_ID { get; set; }
        public Nullable<System.DateTime> EVENT_CREATED { get; set; }
        public string EVENT_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string USER_ID { get; set; }
        
        [JsonIgnore]
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
